CC=g++
CXX=g++
CXXFLAGS=-Wall -Wextra -Wsign-conversion -O2
.PHONY : clean

all: build

build: dreptunghiuri4

ternar: dreptunghiuri4.o

run: dreptunghiuri4
	@./dreptunghiuri4

clean:
	rm -rf *.o *~ *.out dreptunghiuri4
